version: '3'

volumes:
  datafiles:
    
services:

  mysqllocal:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_DATABASE: dbAssignment4
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      TZ: America/Toronto
    ports:
      - "3306:3306"

  assignment4cloud:
    image: eduardoamparo/assignment4-cloud
    restart: always
    ports:
     - 8761:8761
    depends_on:
     - mysqllocal

  assignment4service1:
    image: eduardoamparo/assignment4-service1
    restart: always
    ports:
     - 8010:8010
    depends_on:
     - assignment4cloud

  assignment4web1:
    image: eduardoamparo/assignment4-web1
    restart: always
    ports:
     - 8011:8011
    depends_on:
     - assignment4cloud

  assignment4service2:
    image: eduardoamparo/assignment4-service2
    restart: always
    ports:
     - 8020:8020
    depends_on:
     - assignment4cloud

  assignment4web2:
    image: eduardoamparo/assignment4-web2
    restart: always
    ports:
     - 8021:8021
    depends_on:
     - assignment4cloud

     



